name: MDE

options:
  defaultConfig: Debug
  developmentLanguage: en
  deploymentTarget:
    macOS: "14.0"

packages:
  MarkdownEditor:
    url: https://github.com/Pallepadehat/MarkdownEditor.git
    from: 1.0.0

targets:
  MDE:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: MDE
        excludes:
          - Info.plist
          - MDE.entitlements
          - MDE.xcodeproj
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ohffs.MDE
        DEVELOPMENT_TEAM: S8JFC974Y7
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: 5.0
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: MDE/Info.plist
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_APP_SANDBOX: NO
        CODE_SIGN_ENTITLEMENTS: MDE/MDE.entitlements
        MACOSX_DEPLOYMENT_TARGET: 14.0
    info:
      path: MDE/Info.plist
    entitlements:
      path: MDE/MDE.entitlements
    dependencies:
      - package: MarkdownEditor
